### ISSUE TITLE
yc-400 and YC-412 dimmers are added as switches

### ISSUE THREAD

**Issue by B3rt** [athombv/nl.klikaanklikuit#12]
I today added 2x YC-400 and 1x YC412 klikaanklikuit dimmers but all 3 device where added as on/off switch.

Looks like there is somthing going wrong and the device is not reqonized correctly, in the appstore these device are listed as supported.

The do work as on/off switch, but there is no way to set any dim level.

Hope this can be fixed.

**Comment by bvdbos** [comment]
For the 412, that's an on/off device according to the driver.js:
https://github.com/athombv/nl.klikaanklikuit/blob/master/drivers/YC-412/driver.js
Is the YC-400 supported? It's not in the list with drivers?

**Comment by B3rt** [comment]
both are dimmers, it eis even mentioed on the device it self, so no switches!

Also both models are listed as supported devices in the app store device list.

**Comment by BasKiers** [comment]
Hi, 

I am sorry but the dim level of those switches cannot be controlled by Homey. This is because the signal to those switches only supports an on/off commando. 

The way dimming works on those switches is by holding the on button on the remote and waiting for the socket to loop through its dim levels like a sinus function. The problem is that even if it can be implemented that Homey sends a long press signal and after a set time (for instance 400 milliseconds) sends the on signal again to stop the dim cycle there is no guarantee that the socket is at the preferred dim state. Homey has no way to know at what state the socket is and how long the state should cycle to change to a preferred state. New KlikAanKlikUit switches (model numbers starting with an A) support the cycling of the dim value as well as a DIM command in the signal which can be send by a remote. This makes Homey able to send a DIM command with the preferred brightness to change the socket to the dim state. If the user later changes the dim value with his/her remote Homey is still able to send the dim value through this DIM command and is not dependent on the current state of the socket like with these old sockets.

Regards,
Bas
