### ISSUE TITLE
AWMR-300 will not activate

### ISSUE THREAD

**Issue by HermanHSlagman** [athombv/nl.klikaanklikuit#23]
Dear supporter,
I have bought another AWMR-300 receiver.
Now I try to activate that. In the `activate learning-mode` process, the Homey will not connect to the receiver.
Other receivers of the same type that I previously incorporated into the Homey network are working well.

**Comment by BasKiers** [comment]
Hi,

This is probably caused by the memory of the device being full. Please consult the user manual on how to clear the memory before pairing it to Homey. Normally you can clear the memory by holding the pair button for 8 seconds and after releasing the pair button pressing it another time for 1 second.

Regards,
Bas
