### ISSUE TITLE
Inverting direction should also change flows

### ISSUE THREAD

**Issue by mettin** [athombv/nl.klikaanklikuit#27]
I have a sunshade that is controlled by KlikAanKlikUit.
It is controlled by a flow that says: Close me when it starts to rain
Yesterday I inverted the direction because the wiring was incorrect.
Today it starts to rain and my sunshade opens and I have a wet sunshade, which could have caused serious issues.

Proposed solution:
When clicking the 'invert' and pressing save, there should be a modal asking if i want to invert my flows using this switch.

**Comment by mettin** [comment]
(ASUN-650)

**Comment by BasKiers** [comment]
Hi,

I am currently completing a rewrite to SDK2 which I am planning to release on the beta channel of the KlikAanKlikUit app soon. This will be version 4.0.0.

In the new version I tested your usecase and found that the flowcard has the options up/down/stop. When you did not invert the direction the "up" option will close your blinds like you mentioned. Now if you update the setting to invert the controls the flow card still says "up" and will now also open your blinds. If your suggestion proposes to ask to change all flow card options from "up" to "down" and vice versa when you change the invert setting this is not something I can add to the KaKu app since I cannot change flow cards.

Regards,
Bas

**Comment by mettin** [comment]
So this is impossible since apps don't have access to flows? That makes sense security-wise.

**Comment by BasKiers** [comment]
Indeed. Since the proposed solution is not possible I will close this issue.

Thanks for reporting.
