### ISSUE TITLE
ACDB 7000AC receiver is not working

### ISSUE THREAD

**Issue by JoostSmilde** [athombv/nl.klikaanklikuit#5]
Hi Guys,

I bought myself a ACDB-7000AC doorbel receiver and sender. 

The sender is working fine! But the receiver isn't working. If i want to make a flow when a button is pushed... 

It also won't learn the receiver... 

It's not a world problem, but maybe you can do something about it in the future :)

Cheers,

Joost

**Comment by BasKiers** [comment]
Hi,

Could you check if this issue is range related by trying to pair it close to Homey (<1 meter)?

Regards,
Bas

**Comment by Veldkornet** [comment]
Hi, I have the same issue. 

So basically the ACDB-7000AC is a combination of two devices.
[ACDB-7000C](https://www.klikaanklikuit.nl/nl/acdb-7000c-draadloze-deurbel.html) - The doorbell itself
[ACDB-7000A](https://www.klikaanklikuit.nl/nl/acdb-7000a-draadloze-drukknop.html) - The button


So basically, I have a flow which states that when the doorbell goes off, a push notification should be sent to my phone. Except, when the doorbell is pushed, nothing happens.

However, if you reverse the flow, and say that if the door opens, then the doorbell should go off, that works fine. So I can make the doorbell ring as often as I like with the relevant flows. But it's not picking up that the doorbell rang in order to start a flow.

On a side note, could you add support for the ACDB-7000A button itself?

**Comment by gratjetost** [comment]
I got it working. with my ACDB-7000C. I can teach the button separately from the receiver.
the only thing I found it doesn't show up in the insight graphs.

**Comment by Veldkornet** [comment]
Hmm, can you detail the workaround for adding the button? I tried with my ACDB-7000A, but it doesn't work.

**Comment by gratjetost** [comment]
@Veldkornet I just added my button. nothing special things or workaround.
selected the ADCB-7000C from the list. selected the button. pressed next. when homey asked to press the button I did. and it worked.

**Comment by Veldkornet** [comment]
Ah okay thanks. Doesn't seem to work for me with the ACDB-7000A.

**Comment by Veldkornet** [comment]
So I saw that the ACDB-6600 in Homey has the ACDB-7000A as it's button. So I tried adding this instead. However:

- By default, no matter how much I tried, it just wouldn't add.
- So I moved the Homey literally RIGHT next to the button (as in within 10 centimetres), and after about 15 tries, it eventually added the button
- However after moving Homey back to its normal position, it's not working again. It's pretty much useless.

So hopefully, you guys can:
A) Fix the ACDB-7000C so that it correctly triggers when the doorbell rings
and
B) Add the buttons (ACDB-7000A & ACDB-7000B) as separate devices, and hopefully fix the range while at it.

I should also mention that the HomeWizard was working fine with the button and the same distance. So I don't think it's a distance issue and I expect that can be resolved easily.

**Comment by flexann** [comment]
I have 2 buttons and 2 doorbells. Each button should evoke it's own dedicated sound on both doorbells. But pushing either button causes the default sound to be played. Did anyone get this going?

**Comment by Veldkornet** [comment]
I've tried now with Firmware 1.2.2, and no difference.
The ACDB-7000A is really only 2m away, and the Smartwares door sensor (which is right next to it) works fine.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2655
